### ISSUE TITLE
Causes Server Rendering to fail?

### ISSUE THREAD

**Issue by shirshak55** [byteboomers/vue-prom#4]
when i try to import it says 

```

ReferenceError: window is not defined
    at Object.<anonymous> (/Users/shirshak/Desktop/code/project-parley/node_modules/vue-prom/dist/vue-prom.js:1:215)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at r (/Users/shirshak/Desktop/code/project-parley/node_modules/vue-server-renderer/build.dev.js:9300:16)
    at Object.vue-prom (webpack:/external "vue-prom":1:0)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at Module../node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./src/components/ShowParley.vue?vue&type=script&lang=js& (main.3c7e0c3987f90aeccdc6.js:583:66)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at Module../src/components/ShowParley.vue?vue&type=script&lang=js& (src/components/ShowParley.vue?b36e:1:0)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at Module../src/components/ShowParley.vue (src/components/ShowParley.vue:1:0)
    at __webpack_require__ (webpack/bootstrap:19:0)
```

**Comment by shirshak55** [comment]
thanks for tweet link . I found this package and it worked for server side rendering too.

https://github.com/posva/vue-promised

**Comment by botre** [comment]
Thank you for the report, I have added SSR support now 👍

https://github.com/Botre/vue-prom/commit/d2e0e22723346224f559f0bfd937d50f0be8bc0b

**Comment by shirshak55** [comment]
Thanks :)
